import torch
import torch.nn as nn
torch.manual_seed(123)
batch = torch.randn(2,5)
print(batch)
layer = nn.Sequential(nn.Linear(5,6),nn.ReLU())
output = layer(batch)
print(output)
mean = output.mean(dim=-1,keepdim =True)
variance = output.var(dim=-1,keepdim = True)
print(f"Mean : {mean}")
print(f"Variance : {variance}")
normalization_output=(output - mean) / (variance ** 0.5)
print(normalization_output)
mean = normalization_output.mean(dim=-1,keepdim=True)
variance = normalization_output.var(dim=-1,keepdim=True)
torch.set_printoptions(sci_mode=False)
print(mean)
print(variance)